### ISSUE TITLE
Optimize WinSBX Speed [3/2/22]

### ISSUE THREAD

**Issue by danimalquackers** [dannytech/cc-sec-440#17]
Try to identify what makes WinSBX so slow in certain situations. From basic testing, Nested Virtualization seriously impacts performance, but it still has a fairly slow startup time. Would be good to identify and track down common errors from things like installing Office.

**Comment by danimalquackers** [comment]
Nothing can really be done to optimize, as far as I can tell. The hardware just needs to support it well, and as far as I can tell, this means a fast CPU (memory is less important), and ideally not running with nested virtualization, which appears to seriously cripple performance, maxing out the CPU when it should mostly be idling. Looking up crashes like `0x80072746` also yielded no usable results.

**Comment by danimalquackers** [comment]
Noticed that that specific error appears to also lead to the 0 byte bug, so it is imperative to avoid it happening.

**Comment by dannytech** [comment]
Also added a message after installation to show when it's complete.
